Task- 1:


Create a Python program that converts between different units of measurement.  • The program should:
 1. Prompt the user to choose the type of conversion (e.g., length, weight, volume).
 2. Ask the user to input the value to be converted.
 3. Perform the conversion and display the result.
 4. Handle potential errors, such as invalid input or unsupported conversion types.
 • Requirements:
 1. Functions: Define at least one function to perform the conversion.
 2. Error Handling: Use try-except blocks to handle invalid input (e.g., non-numeric values).
 3. User Input: Prompt the user to select the conversion type and input the value.
 4. Docstrings: Include a docstring in your function to describe its purpose, parameters, and
 return value.
 • Conversion Options:
 1. Length:– Convert meters (m) to feet (ft).– Convert feet (ft) to meters (m).
 2. Weight:– Convert kilograms (kg) to pounds (lbs).– Convert pounds (lbs) to kilograms (kg).
 3. Volume:– Convert liters (L) to gallons (gal).– Convert gallons (gal) to liters (L).

In [ ]:
print("Choose the type conversion that you want: ")
print("1. Length \n 2. Weight \n 3. Volume")
choice = input()

#for length conversion
if choice == '1' or choice.lower() == "length":
  print("Choose the type of conversion you want below: ")
  print("1. Meters(m) to Feet(ft) \n 2. Feet(ft) to Meters(m)")
  choice1 = input()

  print("Enter the value:")

  try:
    num = float(input())
    if choice1 == '1' or choice1.lower() == "meters" or choice1 =="m":
      value=mtoft(num)
      print(f"The converted value is:  {value:.2f} feet")
    elif choice1 == '2' or choice1.lower() == "feet" or choice1 == "ft":
      value=fttom(num)
      print(f"The converted value is: {value:.2f} meters")
    else:
      print("Invalid Input. ")
  except ValueError:
    print("Please input a valid number for the value.")

#for weight conversion
elif choice == '2' or choice.lower() == "weight":
  print("Choose the type of conversion you want below: ")
  print("1. Kilograms (kg) to Pounds (lbs) \n2. Pounds (lbs) to Kilograms (kg)")
  choice2 = input()

  print("Enter the value:")

  try:
    num = float(input())
    if choice2 == '1' or choice2.lower() == "kilograms" or choice2 =="kg":
      value=kgtolb(num)
      print(f"The converted value is:  {value:.2f} lbs.")
    elif choice2 == '2' or choice2.lower() == "pounds" or choice2 == "lbs":
      value=lbtokg(num)
      print(f"The converted value is: {value:.2f} kg.")
    else:
      print("Invalid Input. ")
  except ValueError:
    print("Please input a valid number for the value.")

#for volume conversion
elif choice == '3' or choice.lower() == "volume":
  print("Choose the type of conversion you want below: ")
  print("1. Litres (L) to Gallons (gal) \n2. Gallons (gal) to Litres (L)")
  choice3 = input()

  print("Enter the value:")
  try:
    num = float(input())
    if choice3 == '1' or choice3.lower() == "litres" or choice3.lower =="l":
      value= ltogal(num)
      print(f"The converted value is:  {value:.2f} gal.")
    elif choice3 == '2' or choice3.lower() == "gallons" or choice3 == "gal":
      value=galtol(num)
      print(f"The converted value is: {value:.2f} L.")
    else:
      print("Invalid Input. ")
  except ValueError:
    print("Please input a valid number for the value.")

def mtoft(m):
    """
    Converts meters to feet.
    Parameters:
    m (float): The value in meters to be converted.
    Returns:
    float: The converted value in feet.
    """
    ft = m * 3.28084
    return ft

def fttom(ft):
    """
    Converts feet to meters.
    Parameters:
    ft (float): The value in feet to be converted.
    Returns:
    float: The converted value in meters.
    """
    m = ft * 0.3048
    return m

def kgtolb(kg):
    """
    Converts kilograms to pounds.
    Parameters:
    kg (float): The value in kilograms to be converted.
    Returns:
    float: The converted value in pounds.
    """
    lb = kg * 2.20462
    return lb

def lbtokg(lb):
    """
    Converts pounds to kilograms.
    Parameters:
    lb (float): The value in pounds to be converted.
    Returns:
    float: The converted value in kilograms.
    """
    kg = lb * 0.453592
    return kg

def ltogal(l):
    """
    Converts liters to gallons.
    Parameters:
    l (float): The value in liters to be converted.
    Returns:
    float: The converted value in gallons.
    """
    gal = l * 0.264172
    return gal

def galtol(gal):
    """
    Converts gallons to liters.
    Parameters:
    gal (float): The value in gallons to be converted.
    Returns:
    float: The converted value in liters.
    """
    l = gal * 3.78541
    return l




Choose the type conversion that you want: 
1. Length 
 2. Weight 
 3. Volume
3
Choose the type of conversion you want below: 
1. Litres (L) to Gallons (gal) 
2. Gallons (gal) to Litres (L)
1
Enter the value:
3
The converted value is:  0.79 gal.


Task -2
 Create a Python program that performs various mathematical operations on a list of numbers.
 • The Program should:
 1. Prompt the user to choose an operation (e.g., find the sum, average, maximum, or minimum
 of the numbers).
 2. Ask the user to input a list of numbers (separated by spaces).
 18

 3. Perform the selected operation and display the result.
 4. Handle potential errors, such as invalid input or empty lists.
 • Requirements:
 1. Functions: Define at least one function for each operation (sum, average, maximum, mini
mum).
 2. Error Handling: Use try-except blocks to handle invalid input (e.g., non-numeric values or
 empty lists).
 3. User Input: Prompt the user to select the operation and input the list of numbers.
 4. Docstrings: Include a docstring in each function to describe its purpose, parameters, and
 return value.


In [132]:
def find_sum(n):
  """
  Calculates the sum of a list of numbers.
  Parameters:
  n (list): A list of numbers.
  Returns:
  float: The sum of the numbers in the list.
  """
  total = 0
  for num in n:
      total += n
  return total

def find_avg(n):
  """
  Calculates the average of a list of numbers.
  Parameters:
  n (list): A list of numbers.
  Returns:
  float: The average of the numbers in the list.
  """
  return sum(n)/len(n)

def find_max(n):
  """
  Finds the maximum value in the list of numbers.
  Parameters:
  n (list): A list of numbers.
  Returns:
  float: The maximum value in the list.
  """
  total = 0
  count = 0
  for num in n:
      total += num
      count += 1
  return total / count if count > 0 else 0

def find_min(n):
  """
  Finds the minimum value in the list of numbers.
  Parameters:
  n (list): A list of numbers.
  Returns:
  float: The minimum value in the list.
  """
  max_value = n[0]
  for num in n:
      if num > max_value:
          max_value = num
  return max_value



"""
  Prompt user for input to perform chosen operation.
"""
print("Choose the operation to perform: ")
print("1. Sum \n 2. Average \n 3. Maximum \n 4. Minimum")
choice = input("Enter the number of your choice (1-4): ").strip()

try:
  user = input("Enter a list of numbers separated by spaces: ").strip()

  #convert string input to list of numbers and convert to float
  num = [float(x) for x in user.split()]
  if choice == "1":
    value= find_sum(num)
  elif choice == "2":
    value = find_avg(num)
  elif choice == "3":
    value = find_max(num)
  elif choice == "4":
    value = find_min(num)
  else:
    print("Invalid Input. ")

  #Displying the result
  print(f"The result of the operation is: {value}")

except ValueError as e:
  print(f"Error:{e}. Please input a valid number for the value.")
except ZeroDivisionError:
  print("Error: Division by zero.")
except Exception as e:
  print(f"An error has occurred: {e}")


Choose the operation to perform: 
1. Sum 
 2. Average 
 3. Maximum 
 4. Minimum
Enter the number of your choice (1-4): 2
Enter a list of numbers separated by spaces: 3 3 3 6
The result of the operation is: 3.75


 4.2 Exercise on List Manipulation:
 1. Extract Every Other Element:
 Write a Python function that extracts every other element from a list, starting from the first element.
 • Requirements:– Define a function extract
 every
 other(lst) that takes a list lst as input and returns a
 new list containing every other element from the original list.– Example: For the input [1, 2, 3, 4, 5, 6], the output should be [1, 3, 5]

In [ ]:
def extract_every_other(lst):
  #slicing list starting from 0 index 2 steps
  return lst[::2]

list=[1,2,3,4,5,6]
output = extract_every_other(list)
print(output)

[1, 3, 5]


 2. Slice a Sublist:
 Write a Python function that returns a sublist from a given list, starting from a specified index and
 ending at another specified index.
 • Requirements:– Define a function get
 sublist(lst, start, end) that takes a list lst, a starting index
 start, and an ending index end as input and returns the sublist from start to end (inclusive).– Example: For the input [1, 2, 3, 4, 5, 6] with start=2 and end=4, the output should
 be [3, 4, 5].

In [ ]:
def sublist(lst,start,end):
  return lst[start:end+1]

list=[1,2,3,4,5,6]
output = sublist(list,2,4)
print(output)


[3, 4, 5]


 3. Reverse a List Using Slicing:
 Write a Python function that reverses a list using slicing.
 • Requirements:– Define a function reverse
 slicing.
 list(lst) that takes a list lst and returns a reversed list using– Example: For the input [1, 2, 3, 4, 5], the output should be [5, 4, 3, 2, 1]

In [ ]:
def reverse_list(lst):
  #using reverse slicing to list
  return lst[::-1]
list = [1,2,3,4,5]
output = reverse_list(list)
print(output)

[5, 4, 3, 2, 1]


 4. Remove the First and Last Elements:
 Write a Python function that removes the first and last elements of a list and returns the resulting
 sublist.
 • Requirements:– Defineafunction remove
 first
 last(lst) that takes a list lst and returns a sublist without
 the first and last elements using slicing.– Example: For the input [1, 2, 3, 4, 5], the output should be [2, 3, 4]

In [ ]:
def remove_first_last(lst):
  return lst[1:-1]

list = [1,2,3,4,5]
output = remove_first_last(list)
print(output)


[2, 3, 4]


5. Get the First n Elements:
 Write a Python function that extracts the first n elements from a list.
 • Requirements:– Define a function get
 first
 n(lst, n) that takes a list lst and an integer n as input and
 returns the first n elements of the list using slicing.– Example: For the input [1, 2, 3, 4, 5] with n=3, the output should be [1, 2, 3].

In [ ]:
def get_first_n(lst,n):
  return lst[:n]

list = [1,2,3,4,5]
output = get_first_n(list,3)
print(output)


[1, 2, 3]


 6. Extract Elements from the End:
 Write a Python function that extracts the last n elements of a list using slicing.
 • Requirements:– Define a function get
 last
 n(lst, n) that takes a list lst and an integer n as input and
 returns the last n elements of the list.– Example: For the input [1, 2, 3, 4, 5] with n=2, the output should be [4, 5].

In [ ]:
def get_last_n(lst,n):
  return lst[-n:]

list = [1,2,3,4,5]
output = get_last_n(list,2)
print(output)


[4, 5]


7. Extract Elements in Reverse Order:
 Write a Python function that extracts a list of elements in reverse order starting from the second-to-last
 element and skipping one element in between.
 • Requirements:– Define a function reverse
 skip(lst) that takes a list lst and returns a new list containing
 every second element starting from the second-to-last, moving backward.– Example: For the input [1, 2, 3, 4, 5, 6], the output should be [5, 3, 1]

In [ ]:
def reverse_skip(lst):
  #start from second_to_last containing every second element moving backward
  return lst[-2::-2]

list = [1,2,3,4,5,6]
output = reverse_skip(list)
print(output)

[5, 3, 1]


 4.3 Exercise on Nested List

 1. Flatten a Nested List:
 Write a Python function that takes a nested list and flattens it into a single list, where all the elements
 are in a single dimension.
 • Requirements:– Define a function flatten(lst) that takes a nested list lst and returns a flattened version
 of the list.– Example: For the input [[1, 2], [3, 4], [5]], the output should be [1, 2, 3, 4, 5]

In [ ]:
def flatten(lst):
  #list comprehension
  return [i for sublist in lst for i in sublist]

input=[[1,2],[3,4],[5]]
output=flatten(input)
print(output)

[1, 2, 3, 4, 5]


 2. Accessing Nested List Elements:
 Write a Python function that extracts a specific element from a nested list given its indices.
 • Requirements:– Define a function access
 nested
 element(lst, indices) that takes a nested list lst and
 a list of indices indices, and returns the element at that position.– Example: For the input lst = [[1, 2, 3], [4, 5, 6], [7, 8, 9]] with indices = [1,
 2], the output should be 6

In [ ]:
def access_nested_element(lst,idices):
  for i in idices:
    lst = lst[i]
  return lst
input_lst= [[1, 2, 3], [4, 5, 6], [7, 8, 9]]
output=access_nested_element(input_lst,[1,2])
print(output)

6


 3. Sum of All Elements in a Nested List:
 Write a Python function that calculates the sum of all the numbers in a nested list (regardless of depth).
 • Requirements:– Define a function sum
 nested(lst) that takes a nested list lst and returns the sum of all
 the elements.– Example: For the input [[1, 2], [3, [4, 5]], 6], the output should be 21

In [ ]:
def sum_nested(lst):
    total = 0
    for item in lst:
        if isinstance(item, list):  # Check if the item is a list
            total += sum_nested(item)  # Recursively sum the nested list
        else:
            total += item  # If it's an integer, add it to the total
    return total

# Example usage
nested_list = [[1, 2], [3, [4, 5]], 6]
result = sum_nested(nested_list)
print(result)  # Output: 21


TypeError: isinstance() arg 2 must be a type, a tuple of types, or a union

 4. Remove Specific Element from a Nested List:
 Write a Python function that removes all occurrences of a specific element from a nested list.
 • Requirements:– Define a function remove
 element(lst, elem) that removes elem from lst and returns the
 modified list.– Example: Fortheinput lst = [[1, 2], [3, 2], [4, 5]]andelem = 2,theoutputshould
 be [[1], [3], [4, 5]]

In [ ]:
def remove_element(lst,elem):
  for i in lst:
    while elem in i:
      i.remove(elem)
  return lst

input_lst = [[1, 2], [3, 2], [4, 5]]
output=remove_element(input_lst,2)
print(output)




[[1], [3], [4, 5]]


 5. Find the Maximum Element in a Nested List:
 Write a Python function that finds the maximum element in a nested list (regardless of depth).
 • Requirements:– Define a function find
 element.
 max(lst) that takes a nested list lst and returns the maximum– Example: For the input [[1, 2], [3, [4, 5]], 6], the output should be 6.

In [ ]:
def find_max(lst):
  for item in lst:
    if isinstance(item, list):
      max_value = max(max_value, find_max(item))
    else:
        max_value = max(max_value, item)  # Otherwise, compare the item with max_value
  return max_value
nested_list = [[1, 2], [3, [4, 5]], 6]
result = find_max(nested_list)
print(result)

TypeError: isinstance() arg 2 must be a type, a tuple of types, or a union

 6. Count Occurrences of an Element in a Nested List:
 Write a Python function that counts how many times a specific element appears in a nested list.
 • Requirements:– Define a function count
 occurrences(lst, elem) that counts the occurrences of elem in
 the nested list lst.– Example: Fortheinput lst = [[1, 2], [2, 3], [2, 4]]andelem = 2,theoutputshould
 be 3.

In [ ]:
def count_occurrences(lst, elem):
    count = 0
    for item in lst:
        if isinstance(item, list):  # Check if the item is a list
            count += count_occurrences(item, elem)  # Recursively count in sublist
        else:
            if item == elem:  # If the item is equal to the element we're looking for
                count += 1
    return count

# Example usage
nested_list = [[1, 2], [2, 3], [2, 4]]
element_to_count = 2
result = count_occurrences(nested_list, element_to_count)
print(result)  # Output: 3


TypeError: isinstance() arg 2 must be a type, a tuple of types, or a union

 7. Flatten a List of Lists of Lists:
 Write a Python function that flattens a list of lists of lists into a single list, regardless of the depth.
 • Requirements:– Define a function deep
 flatten(lst) that takes a deeply nested list lst and returns a single
 f
 lattened list.– Example: For the input [[[1, 2], [3, 4]], [[5, 6], [7, 8]]], the output should be
 [1, 2, 3, 4, 5, 6, 7, 8].

In [ ]:
def deep_flatten(lst):
    flattened = []
    for item in lst:
        if isinstance(item, list):
            flattened.extend(deep_flatten(item))
        else:
            flattened.append(item)
    return flattened
input = [[[1, 2], [3, 4]], [[5, 6], [7, 8]]]
output = deep_flatten(input)
print(output)

TypeError: isinstance() arg 2 must be a type, a tuple of types, or a union

 8. Nested List Average:
 Write a Python function that calculates the average of all elements in a nested list.
 • Requirements:– Define a function average
 of all the elements.
 nested(lst) that takes a nested list lst and returns the average– Example: For the input [[1, 2], [3, 4], [5, 6]], the output should be 3.5

In [ ]:
def average_of_all_elements_nested(lst):
    # Flatten the nested list first
    def deep_flatten(lst):
        flattened


 10 To- Do- NumPy
 Please complete all the problems listed below:

 10.1 Basic Vector and Matrix Operation with Numpy.

Problem- 1: Array Creation:
 Complete the following Tasks:
 1. Initialize an empty array with size 2X2.


In [5]:
import numpy as np
#storing none python object to create empty array
emptyarr = np.empty((2, 2),dtype=object)
print(emptyarr)

[[None None]
 [None None]]


 2. Initialize an all one array with size 4X2.



In [7]:
one_arr= np.ones((3,2))
print(one_arr)

[[1. 1.]
 [1. 1.]
 [1. 1.]]


 3. Return a new array of given shape and type, filled with fill value.{Hint: np.full}


In [12]:
#full function with shape and filled with fill value(13)
fill_arr=np.full((4,2),13)
print(fill_arr)


[[13 13]
 [13 13]
 [13 13]
 [13 13]]


4. Return a new array of zeros with same shape and type as a given array.{Hint: np.zeros like}


In [14]:
#creating same shape and type of array as before but values filled with zero
zero_arr=np.zeros_like(fill_arr)
print(zero_arr)

[[0 0]
 [0 0]
 [0 0]
 [0 0]]


 5. Return a new array of ones with same shape and type as a given array.{Hint: np.ones like}


In [15]:
#creating same shape and type of array as before but values filled with ones
ones_arr=np.ones_like(zero_arr)
print(ones_arr)

[[1 1]
 [1 1]
 [1 1]
 [1 1]]


 6. For an existing list new_list = [1,2,3,4] convert to an numpy array.{Hint: np.array()}

In [16]:
new_list=[1,2,3,4]
#converting list to array using numpy
np_arr=np.array(new_list)
print(np_arr)

[1 2 3 4]


 Problem- 2: Array Manipulation: Numerical Ranges and Array indexing:
 Complete the following tasks:
 1. Create an array with values ranging from 10 to 49. {Hint:np.arrange()}.

In [18]:
#arange function doesn't include stop-value
range_arr=np.arange(10,50)
print(range_arr)

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]


2. Create a 3X3 matrix with values ranging from 0 to 8.
 {Hint:look for np.reshape()}

In [22]:
#creating a 1D array from 0-8
ara=np.arange(0,9)
#shaping 1D array to 3D square array
mat=ara.reshape(3,3)
print(mat)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


 3. Create a 3X3 identity matrix.{Hint:np.eye()

In [23]:
#identity consists of squared matrix of 0-1
id_mat=np.eye(3)
print(id_mat)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


 4. Create a random array of size 30 and find the mean of the array.

In [31]:
rand= np.random.random(30)
#calculate mean using built-in mean()
mean_arr=rand.mean()
print(mean_arr)

0.5198178764761849


 5. Create a 10X10 array with random values and find the minimum and maximum values

In [39]:
#generate 10D array of random values
rand=np.random.random((10,10))
max_value=rand.max()
min_value=rand.min()
print(f"Maximum value:{max_value}")
print(f"Minimum value:{min_value}")

Maximum value:0.9924301158204863
Minimum value:0.02248475882697376


 6. Create a zero array of size 10 and replace 5th element with 1

In [40]:
#Generating 1D zero array of size 10
zer= np.zeros(10)
#Replace 5th element with 1 by indexing
zer[4]=1
print(zer)

[0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]


 7. Reverse an array arr = [1,2,0,0,4,0].

In [42]:
arr = [1,2,0,0,4,0]
#reverse slicing operation
rev = arr[::-1]
print(f"Reversed array is: {rev}")

Reversed array is: [0, 4, 0, 0, 2, 1]


 8. Create a 2d array with 1 on border and 0 inside.

In [48]:
#generating 2D zero array with 7 rows and columns
arr = np.zeros((7,7))
#setting elements of first row to 1
arr[0,:] = 1

#set elements of last row to 1
arr[-1,:] = 1
print(arr)

[[1. 1. 1. 1. 1. 1. 1.]
 [0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0.]
 [1. 1. 1. 1. 1. 1. 1.]]


 9. Create a 8X8 matrix and fill it with a checkerboard pattern

In [58]:
arr = np.zeros((8,8))
#fill value 1 to even rows and column indexes
arr[::2, ::2] = 1

#fill value 0 to odd rows and column indexes
arr[1::2, 1::2] = 1
print(arr)

[[1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]]


Problem- 3: Array Operations:
 For the following arrays

 x = np.array([[1,2],[3,5]]) and y = np.array([[5,6],[7,8]]);
 v = np.array([9,10]) and w = np.array([11,12])

In [60]:
x = np.array([[1,2],[3,5]])
y = np.array([[5,6],[7,8]])
v = np.array([9,10])
w = np.array([11,12])

Complete all the tasks using numpy

1. Add the two array.

In [73]:
ad= np.add(x,y)
print(f"{x} + {y} = {ad} \n")

ad1= np.add(v,w)
print(f"{v} + {w} = {ad1}")

[[1 2]
 [3 5]] + [[5 6]
 [7 8]] = [[ 6  8]
 [10 13]] 

[ 9 10] + [11 12] = [20 22]


2. Subtract the two array.

In [77]:
sub1 = np.subtract(y,x)
print(f"y-x={sub1}")
sub2 = np.subtract(w,v)
print(f"w-v={sub2}")

y-x=[[4 4]
 [4 3]]
w-v=[2 2]


 3. Multiply the array with any integers of your choice.

In [81]:
mul1 = np.multiply(2,x)
print(f"2*x={mul1}")
mul2 = np.multiply(2,y)
print(f"2*y={mul2}")
mul3 = np.multiply(3,v)
print(f"3*v={mul3}")
mul4 = np.multiply(7,w)
print(f"7*w={mul4}")




2*x=[[ 2  4]
 [ 6 10]]
2*y=[[10 12]
 [14 16]]
3*v=[27 30]
7*w=[77 84]


 4. Find the square of each element of the array

In [82]:
sqrx = np.square(x)
sqry = np.square(y)
sqrv = np.square(v)
sqrw = np.square(w)
print(f"x**2={sqrx}")
print(f"y**2={sqry}")
print(f"v**2={sqrv}")
print(f"w**2={sqrw}")


x**2=[[ 1  4]
 [ 9 25]]
y**2=[[25 36]
 [49 64]]
v**2=[ 81 100]
w**2=[121 144]


5. Find the dot product between: v(and)w ; x(and)v ; x(and)y.

In [83]:
dotvw = np.dot(v,w)
print(f"Dot product between v and w is {dotvw}")
dotxv = np.dot(x,v)
print(f"Dot product between x and v is {dotxv}")
dotxy = np.dot(x,y)
print(f"Dot product between x and y is {dotxy}")

Dot product between v and w is 219
Dot product between x and v is [29 77]
Dot product between x and y is [[19 22]
 [50 58]]


6. Concatenate x(and)y along row and Concatenate v(and)w along column

In [89]:
xy_concat = np.vstack((x,y))
print("Concatenate x and y along rows: ",xy_concat)

v1 = v.reshape(-1,1)
w1 = w.reshape(-1,1)
vw_concat = np.concatenate((v1,w1),axis=1)
print("Concatenate v and w along columns: ",vw_concat)

Concatenate x and y along rows:  [[1 2]
 [3 5]
 [5 6]
 [7 8]]
Concatenate v and w along columns:  [[ 9 11]
 [10 12]]


 7. Concatenate x(and)v; if you get an error, observe and explain why did you get the error

In [133]:
try:
  concat_xv = np.concatenate((x, v), axis=0)
  #shapes of the arrays don't have same number of dimensions
  print("Concatenation of x and v along rows:", concat_xv)
except ValueError as e:
    print("\nError when concatenating x and v:", e)


Error when concatenating x and v: all the input arrays must have same number of dimensions, but the array at index 0 has 2 dimension(s) and the array at index 1 has 1 dimension(s)


Problem- 4: Matrix Operations:
 • For the following arrays:
 A = np.array([[3,4],[7,8]]) and B = np.array([[5,3],[2,1]]);
 Prove following with Numpy:

1. Prove A.A−1 = I.

In [95]:
A = np.array([[3,4],[7,8]])
B = np.array([[5,3],[2,1]])
#calculate A-1
Arev = np.linalg.inv(A)

#calculate A*A-1
Ii = np.dot(A,Arev)
I = np.round(Ii, decimals=13)

print(I)


[[1. 0.]
 [0. 1.]]



 2. Prove AB= BA.

In [100]:
A = np.array([[3,4],[7,8]])
B = np.array([[5,3],[2,1]])
AB = np.dot(A,B)
BA = np.dot(B,A)
print("Dot product of A and B is: \n", AB)
print("Dot product of B and A is: \n", BA)


Dot product of A and B is: 
 [[23 13]
 [51 29]]
Dot product of B and A is: 
 [[36 44]
 [13 16]]



 3. Prove (AB)T = BTAT

In [103]:
A = np.array([[3,4],[7,8]])
B = np.array([[5,3],[2,1]])
AB = np.dot(A,B)
BA = np.dot(B,A)
ABT = AB.T
BT = B.T
AT = A.T
BTAT = np.dot(BT,AT)
print("(AB)T is: \n", ABT)
print("BTAT is: \n", BTAT)

(AB)T is: 
 [[23 51]
 [13 29]]
BTAT is: 
 [[23 51]
 [13 29]]


 Solve the following system of Linear equation using Inverse Methods.
 2x −3y+z =−1
 x −y+2z =−3
 3x +y−z =9

In [108]:
'''2x −3y+z =−1
 x −y+2z =−3
 3x +y−z =9 defining in matrix form'''
A = np.array([[2,-3,1],[1,-1,2],[3,1,-1]])
B = np.array([-1,-3,9])


Now: solve the above equation using np.linalg.inv function.{Explore more about ”linalg” func
tion of Numpy

In [109]:
Ainv = np.linalg.inv(A)
#A.X = B
#X = A-1*B
X = np.dot(Ainv,B)
print("[x y z] is : \n",X)

[x y z] is : 
 [ 2.  1. -2.]


 10.2 Experiment: How Fast is Numpy?
 In this exercise, you will compare the performance and implementation of operations using plain Python
 lists (arrays) and NumPy arrays. Follow the instructions:

1. Element-wise Addition:
 • Using Python Lists, perform element-wise addition of two lists of size 1,000,000. Measure
 and Print the time taken for this operation.

In [115]:
import time
list1 = [i for i in range(1, 1000001)]
list2 = [i for i in range(1,1000001)]
n = len(list1)
#measure time
starttime = time.time()

#calculating through element wise addition
value = [list1[i] + list2[i] for i in range(n)]
endtime = time.time()
print("Time taken for element-wise addition: ", endtime - starttime, "seconds")

Time taken for element-wise addition:  0.08153200149536133 seconds


 Using Numpy Arrays, Repeat the calculation and measure and print the time taken for
 this operation.

In [119]:
import numpy as np
import time
arr1 = np.arange(1,100001)
arr2 = np.arange(1,100001)
#calculate time taken for element-wise addition
starttime = time.time()
value = arr1 + arr2
endtime = time.time()
print("Time taken for element-wise addition: ", endtime - starttime, "seconds")

Time taken for element-wise addition:  0.00042748451232910156 seconds


2. Element-wise Multiplication
 • Using Python Lists, perform element-wise multiplication of two lists of size 1,000,000.
 Measure and Print the time taken for this operation.


In [120]:
import time
list1 = [i for i in range(1, 1000001)]
list2 = [i for i in range(1,1000001)]
n = len(list1)
#measure time
starttime = time.time()

#calculating through element wise addition
value = [list1[i] * list2[i] for i in range(n)]
endtime = time.time()
print("Time taken for element-wise multiplication: ", endtime - starttime, "seconds")

Time taken for element-wise multiplication:  0.12313318252563477 seconds


 • Using Numpy Arrays, Repeat the calculation and measure and print the time taken for
 this operation.

In [121]:
import numpy as np
import time
arr1 = np.arange(1,100001)
arr2 = np.arange(1,100001)
#calculate time taken for element-wise addition
starttime = time.time()
value = arr1 * arr2
endtime = time.time()
print("Time taken for element-wise addition: ", endtime - starttime, "seconds")

Time taken for element-wise addition:  0.0006148815155029297 seconds


 3. Dot Product
 • Using Python Lists, compute the dot product of two lists of size 1,000,000. Measure and
 Print the time taken for this operation.


In [123]:
import time

# Creating two lists of size 1,000,000
list1 = range(1, 1000001)
list2 = range(1, 1000001)

# Calculating start time
starttime = time.time()

# Calculating the dot product
dot_product = sum([list1[i] * list2[i] for i in range(len(list1))])

# Calculating end time
endtime = time.time()

# Print the time taken
print("Time taken for dot product:", endtime - starttime, "seconds")


Time taken for dot product: 0.24595165252685547 seconds


• Using Numpy Arrays, Repeat the calculation and measure and print the time taken for
 this operation.

In [122]:
import numpy as np
import time

# Creating two arrays of size 1,000,000
arr1 = np.arange(1, 1000001)
arr2 = np.arange(1, 1000001)

# Measuring the time taken
starttime = time.time()

# Performing dot product
dot_product = np.dot(arr1, arr2)

endtime = time.time()

# Printing the time taken for the operation
print("Time taken for dot product:", endtime - starttime, "seconds")

Time taken for dot product: 0.0051648616790771484 seconds


4. Matrix Multiplication
 • Using Python lists, perform matrix multiplication of two matrices of size 1000x1000. Measure and print the time taken for this operation.


In [130]:
# Creating two empty 1000*1000 matrices
m1 = []
m2 = []
result = []
for i in range(1000):
  m1.append([7]*1000)
  m2.append([13]*1000)

# Calculating start time
starttime = time.time()

# Performing matrix multiplication
for i in range(1000): # Loop for rows of matrix 1
  row = []
  for j in range(1000): # Loop for columns of matrix 2
    value = 0
    for k in range(1000):
      value += m1[i][k] * m2[k][j]
    row.append(value) # Replace row elements by result of dot product
  result.append(row) # Append all rows to form matrix

# Calculating end time
endtime = time.time()

# Printing the time taken for the operation
print("Time taken for matrix multiplication:", endtime - starttime, "seconds")

Time taken for matrix multiplication: 279.7352395057678 seconds


 • Using NumPy arrays, perform matrix multiplication of two matrices of size 1000x1000.
 Measure and print the time taken for this operation

In [128]:
import numpy as np
import time

# Creating matrix of 1000*1000 size
m1 = np.random.random((1000, 1000))
m2 = np.random.random((1000, 1000))

# Measuring the time taken
starttime = time.time()

# Performing matrix multiplication
value = np.dot(m1, m2)

endtime = time.time()

# Printing the time taken for the operation
print("Time taken for matrix multiplication:", endtime - starttime, "seconds")

Time taken for matrix multiplication: 0.06792473793029785 seconds
